title: MOHIT KUMAR SINGH
logo: 20250422.jpg
description: "I am a passionate software engineer with strong expertise in python and data science. I have a keen interest in machine learning and artificial intelligence, and I am always eager to learn new technologies and improve my skills. I enjoy solving complex problems and building innovative solutions that make a difference."
theme: jekyll-theme-minimal